# Generated by Django 4.2.6 on 2023-11-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuySell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', max_length=20),
        ),
    ]
