# Generated by Django 4.2.6 on 2023-11-19 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuySell', '0002_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
