# Generated by Django 4.2.6 on 2023-11-25 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuySell', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='total_spent',
            new_name='total',
        ),
    ]
