# Generated by Django 4.2.6 on 2023-11-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuySell', '0004_alter_transaction_price_alter_transaction_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='total',
            new_name='total_spent',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
