# Generated by Django 4.2.6 on 2023-11-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuySell', '0005_rename_total_transaction_total_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Please add your notes here', null=True),
        ),
    ]
