# Generated by Django 4.2.6 on 2023-11-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuySell', '0006_alter_transaction_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_spent',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
    ]
