# Generated by Django 4.2.6 on 2023-11-22 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BuySell', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=30)),
                ('transit_number', models.CharField(blank=True, max_length=9)),
                ('routing_number', models.CharField(blank=True, max_length=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BuySell.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('stripe_id', models.CharField(default='', max_length=255)),
                ('transaction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BuySell.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
