# Generated by Django 4.2.6 on 2023-11-27 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentsell',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=1)]),
        ),
    ]
