# Generated by Django 4.2.6 on 2023-11-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentsell',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
