# Generated by Django 4.2.6 on 2023-11-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentbuy',
            name='stripe_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
