# Generated by Django 4.2.6 on 2023-11-27 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_userpaymentsell_account_holder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentsell',
            name='account_holder_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=1)]),
        ),
        migrations.AlterField(
            model_name='userpaymentsell',
            name='account_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userpaymentsell',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpaymentsell',
            name='routing_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='userpaymentsell',
            name='transit_number',
            field=models.CharField(max_length=9),
        ),
    ]
