# Generated by Django 4.2.6 on 2023-11-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
