# Generated by Django 4.2.6 on 2023-11-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
