# Generated by Django 4.2.6 on 2023-11-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_footerlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlist',
            name='link',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
