# Generated by Django 4.2.6 on 2023-11-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.CharField(default='My Watchlist', max_length=255),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='cryptocurrencies',
            field=models.ManyToManyField(to='core.cryptocurrency'),
        ),
    ]
