# Generated by Django 4.2.6 on 2023-11-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportissue",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("in_progress", "In Progress"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
