# Generated by Django 4.2.6 on 2023-11-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportissue",
            name="issue_type",
            field=models.CharField(default="custom", max_length=255),
        ),
    ]
