# Generated by Django 4.2.6 on 2023-11-20 23:16

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_supportissue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportissue",
            name="files",
            field=models.FileField(
                blank=True, null=True, upload_to=support.models.user_upload_path
            ),
        ),
    ]
