# Generated by Django 4.2.6 on 2023-11-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_alter_supportissue_issue_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportissue",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("currency_exchange", "Currency Exchange"),
                    ("buy_sell_orders", "Buy/Sell Orders"),
                    ("portfolio", "Portfolio"),
                    ("purchase", "Purchase"),
                    ("unauthorized_charge", "Unauthorized Charge"),
                    ("refunds", "Refunds"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
