<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-11-18 19:28
=======
# Generated by Django 4.2.6 on 2023-11-20 23:34
>>>>>>> 8710bb0727f0a1faad902cfb90d4829eba16f4d5

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
=======
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
>>>>>>> 8710bb0727f0a1faad902cfb90d4829eba16f4d5
            ],
        ),
    ]
