# Generated by Django 4.2.6 on 2023-10-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='MarketCap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='Volume',
            field=models.IntegerField(),
        ),
    ]
