# Generated by Django 4.2.6 on 2023-10-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_crypto_marketcap_alter_crypto_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='TwentyFourHour',
            new_name='TwentyFourHourFlag',
        ),
    ]
